# Hadolint Configuration for Docker Security
# https://github.com/hadolint/hadolint

# Dockerfile linting rules focusing on security best practices

# Rules to ignore (with justification)
ignored:
  # DL3008: Pin versions in apt-get install
  # - We handle this through base image version pinning
  
  # DL3009: Delete the apt-get lists after installing something
  # - Our multi-stage builds handle cleanup appropriately

# Rules to treat as errors (security-critical)
failure-threshold: error

# Override specific rule severities
override:
  # Security-critical rules (treat as errors)
  DL3000: error  # Use absolute WORKDIR
  DL3001: error  # For some bash commands it makes no sense running them in a Docker container
  DL3002: error  # Last USER should not be root
  DL3003: error  # Use WORKDIR to switch to a directory
  DL3004: error  # Do not use sudo as it leads to unpredictable behavior
  DL3006: error  # Always tag the version of an image explicitly
  DL3007: error  # Using latest is prone to errors if the image will ever update
  DL3008: error  # Pin versions in apt get install
  DL3009: warning  # Delete the apt-get lists after installing something
  DL3010: error  # Use ADD for extracting archives into an image
  DL3011: error  # Valid UNIX ports range from 0 to 65535
  DL3013: error  # Pin versions in pip
  DL3014: error  # Use the -y switch to avoid manual input
  DL3015: error  # Avoid additional packages by specifying --no-install-recommends
  DL3016: error  # Pin versions in npm
  DL3018: error  # Pin versions in apk add
  DL3019: error  # Use the --no-cache switch to avoid the need to use --update and remove /var/cache/apk/*
  DL3020: error  # Use COPY instead of ADD for files and folders
  DL3021: error  # COPY with more than 2 arguments requires the last argument to end with /
  DL3022: error  # COPY --from should reference a previously defined FROM alias
  DL3023: error  # COPY --from should reference a previously defined FROM alias
  DL3024: error  # FROM aliases (stage names) must be unique
  DL3025: error  # Use arguments JSON notation for CMD and ENTRYPOINT arguments
  DL3026: error  # Use only an allowed registry in the FROM image
  DL3027: error  # Do not use apt as it is meant to be an end-user tool
  DL3028: error  # Pin versions in gem install
  DL3029: error  # Do not use --platform flag with FROM
  DL3030: error  # Use the -y switch to avoid manual input
  DL3032: error  # Yum clean all missing
  DL3033: error  # Specify version with yum install -y <package>-<version>
  DL3034: error  # Non-interactive switch missing
  DL3035: error  # Do not use zypper dist-upgrade
  DL3036: error  # Zypper clean missing
  DL3037: error  # Specify version with zypper install -y <package>=<version>
  DL3038: error  # Use the -y switch to avoid manual input
  DL3040: error  # tar cf archive.tar file should be tar cf archive.tar ./file
  DL3041: error  # Specify version with dnf install -y <package>-<version>
  DL3042: error  # Avoid cache directory with dnf clean all
  DL3043: error  # ONBUILD, FROM or MAINTAINER triggered from within ONBUILD instruction
  DL3044: error  # Do not refer to an environment variable in the same RUN statement
  DL3045: error  # COPY --from cannot reference its own FROM alias
  DL3046: error  # useradd without flag -l and high UID will result in excessively large Image
  DL3047: error  # wget without flag --progress will result in excessively bloated build logs
  DL3048: error  # Invalid label key
  DL3049: error  # Label `<label>` is missing
  DL3050: error  # Superfluous label(s) present
  DL3051: error  # Label `<label>` is not a valid URL
  DL3052: error  # Label `<label>` is not a valid email format
  DL3053: error  # Label `<label>` key is not valid
  DL3054: error  # Label `<label>` is not a valid SPDX license identifier
  DL3055: error  # Label `<label>` does not use semantic versioning
  DL3056: error  # Label `<label>` does not use URL format
  DL3057: error  # HEALTHCHECK instruction missing
  DL3058: error  # Label `<label>` is not a valid git hash
  DL3059: error  # Multiple consecutive RUN instructions
  DL3060: error  # yarn cache clean missing
  
  # Style rules (warnings)
  DL4000: warning  # MAINTAINER is deprecated
  DL4001: warning  # Either use Wget or Curl but not both
  DL4003: warning  # Multiple consecutive RUN instructions
  DL4004: warning  # Multiple consecutive RUN instructions
  DL4005: warning  # Use SHELL to change the default shell
  DL4006: warning  # Set the SHELL option -o pipefail before RUN with a pipe in it

# Allowed registries (security control)
allowed-registries:
  - docker.io
  - gcr.io
  - registry-1.docker.io
  - index.docker.io
  - quay.io
  - registry.access.redhat.com

# Required labels for compliance and security
required-labels:
  - maintainer
  - version

# Trusted base images (security control)
trusted-registries:
  - docker.io/library
  - gcr.io/distroless
  - registry.access.redhat.com/ubi8

# Format for output
format: json

# Strict mode for security compliance
strict-labels: true

# Security-focused dockerfile best practices:
# 1. Always use specific image tags, never 'latest'
# 2. Run containers as non-root user
# 3. Use multi-stage builds to minimize attack surface
# 4. Pin all dependency versions
# 5. Remove unnecessary packages and files
# 6. Use trusted base images
# 7. Implement health checks
# 8. Use COPY instead of ADD
# 9. Set proper file permissions
# 10. Minimize number of layers