name: Release Automation Pipeline

on:
  push:
    tags:
      - 'v*.*.*'
  release:
    types: [published, created, prereleased]
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
        - prerelease
      skip_tests:
        description: 'Skip tests (emergency release only)'
        required: false
        default: false
        type: boolean

env:
  NODE_VERSION: '18'
  EXPO_VERSION: 'latest'
  EAS_VERSION: 'latest'

jobs:
  # Release preparation and validation
  prepare_release:
    name: Prepare Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      release_type: ${{ steps.version.outputs.release_type }}
      changelog: ${{ steps.changelog.outputs.changelog }}
      is_prerelease: ${{ steps.version.outputs.is_prerelease }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Determine version
      id: version
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          # Manual release
          release_type="${{ github.event.inputs.release_type }}"
          current_version=$(node -p "require('./package.json').version")
          
          case "$release_type" in
            "major")
              new_version=$(npm version major --no-git-tag-version)
              ;;
            "minor")
              new_version=$(npm version minor --no-git-tag-version)
              ;;
            "patch")
              new_version=$(npm version patch --no-git-tag-version)
              ;;
            "prerelease")
              new_version=$(npm version prerelease --preid=rc --no-git-tag-version)
              ;;
          esac
          
          echo "version=${new_version}" >> $GITHUB_OUTPUT
          echo "release_type=$release_type" >> $GITHUB_OUTPUT
          echo "is_prerelease=$([[ $release_type == 'prerelease' ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
        else
          # Tagged release
          version="${{ github.ref_name }}"
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "release_type=tagged" >> $GITHUB_OUTPUT
          echo "is_prerelease=$([[ $version =~ -rc\.|−alpha\.|−beta\. ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
        fi
    
    - name: Generate changelog
      id: changelog
      run: |
        echo "Generating changelog for version ${{ steps.version.outputs.version }}..."
        
        # Get last tag
        last_tag=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
        
        if [[ -z "$last_tag" ]]; then
          echo "changelog=Initial release" >> $GITHUB_OUTPUT
        else
          # Generate changelog from commits
          changelog=$(git log $last_tag..HEAD --pretty=format:"- %s" --no-merges)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$changelog" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi
    
    - name: Update version files
      if: github.event_name == 'workflow_dispatch'
      run: |
        # Update app.json version
        jq --arg version "${{ steps.version.outputs.version }}" '.expo.version = $version' app.json > app.json.tmp && mv app.json.tmp app.json
        
        # Commit version updates
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add package.json app.json
        git commit -m "chore: bump version to ${{ steps.version.outputs.version }}" || true
        git push || true

  # Quality assurance for release
  release_qa:
    name: Release Quality Assurance
    runs-on: ubuntu-latest
    needs: prepare_release
    if: github.event.inputs.skip_tests != 'true'
    
    strategy:
      matrix:
        check: [lint, test, security, build]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      if: matrix.check == 'lint'
      run: npm run lint
    
    - name: Run comprehensive tests
      if: matrix.check == 'test'
      run: |
        npm run test:coverage
        npm run test:integration --if-present
    
    - name: Security audit
      if: matrix.check == 'security'
      run: |
        npm audit --audit-level moderate
        npx snyk test --severity-threshold=high || echo "Snyk scan completed"
    
    - name: Build verification
      if: matrix.check == 'build'
      run: |
        npx expo export --platform all
        echo "Build verification completed"

  # Production builds for all platforms
  production_build:
    name: Production Build
    runs-on: ubuntu-latest
    needs: [prepare_release, release_qa]
    if: always() && (needs.release_qa.result == 'success' || needs.release_qa.result == 'skipped')
    strategy:
      matrix:
        platform: [android, ios, web]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Setup Expo CLI
      run: npm install -g @expo/cli@${{ env.EXPO_VERSION }}
    
    - name: Setup EAS CLI
      run: npm install -g eas-cli@${{ env.EAS_VERSION }}
    
    - name: Configure production environment
      run: |
        echo "Configuring production build for ${{ matrix.platform }}"
        # Set production environment variables
        export NODE_ENV=production
        export EXPO_ENV=production
        
        # Update app.json for production
        jq '.expo.updates.fallbackToCacheTimeout = 0' app.json > app.json.tmp && mv app.json.tmp app.json
    
    - name: Build for Android
      if: matrix.platform == 'android'
      run: |
        echo "Building Android production release..."
        eas build --platform android --profile production --non-interactive --wait
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}
    
    - name: Build for iOS
      if: matrix.platform == 'ios'
      run: |
        echo "Building iOS production release..."
        eas build --platform ios --profile production --non-interactive --wait
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}
    
    - name: Build Web
      if: matrix.platform == 'web'
      run: |
        echo "Building web production release..."
        npx expo export --platform web --clear
        
        # Optimize web build
        npx workbox generateSW workbox-config.js --if-present || echo "No workbox config"
    
    - name: Upload production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: production-build-${{ matrix.platform }}-${{ needs.prepare_release.outputs.version }}
        path: |
          *.apk
          *.aab
          *.ipa
          web-build/
          dist/
        retention-days: 90

  # Create GitHub release
  create_github_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [prepare_release, production_build]
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download all build artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: production-build-*
        merge-multiple: true
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ needs.prepare_release.outputs.version }}
        release_name: Release ${{ needs.prepare_release.outputs.version }}
        body: |
          ## 🚀 Release ${{ needs.prepare_release.outputs.version }}
          
          ### Changes
          ${{ needs.prepare_release.outputs.changelog }}
          
          ### 📱 Downloads
          - Android APK/AAB files attached
          - iOS IPA file attached
          - Web build deployed automatically
          
          ### 🔍 Verification
          - ✅ All tests passed
          - ✅ Security scans completed
          - ✅ Production builds verified
          
          ### 📊 Build Info
          - Build Number: ${{ github.run_number }}
          - Commit: ${{ github.sha }}
          - Built with Node.js ${{ env.NODE_VERSION }}
          
          ---
          *Generated by StudyBuddy Release Pipeline*
        draft: false
        prerelease: ${{ needs.prepare_release.outputs.is_prerelease }}
    
    - name: Upload Android APK
      if: hashFiles('*.apk') != ''
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: $(find . -name "*.apk" | head -1)
        asset_name: StudyBuddy-${{ needs.prepare_release.outputs.version }}.apk
        asset_content_type: application/vnd.android.package-archive
    
    - name: Upload Android AAB
      if: hashFiles('*.aab') != ''
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: $(find . -name "*.aab" | head -1)
        asset_name: StudyBuddy-${{ needs.prepare_release.outputs.version }}.aab
        asset_content_type: application/octet-stream
    
    - name: Upload iOS IPA
      if: hashFiles('*.ipa') != ''
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: $(find . -name "*.ipa" | head -1)
        asset_name: StudyBuddy-${{ needs.prepare_release.outputs.version }}.ipa
        asset_content_type: application/octet-stream

  # Deploy to app stores
  deploy_stores:
    name: Deploy to App Stores
    runs-on: ubuntu-latest
    needs: [prepare_release, create_github_release]
    if: needs.prepare_release.outputs.is_prerelease == 'false'
    strategy:
      matrix:
        store: [google_play, app_store]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: production-build-*
        merge-multiple: true
    
    - name: Deploy to Google Play Store
      if: matrix.store == 'google_play' && hashFiles('*.aab') != ''
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
        packageName: com.cognoco.studybuddy
        releaseFiles: "*.aab"
        track: production
        status: completed
        inAppUpdatePriority: 2
        whatsNewDirectory: fastlane/metadata/android/en-US/changelogs/
    
    - name: Deploy to App Store Connect
      if: matrix.store == 'app_store' && hashFiles('*.ipa') != ''
      run: |
        # Install fastlane
        gem install fastlane
        
        # Upload to TestFlight and submit for review
        fastlane ios upload_to_testflight
        fastlane ios submit_for_review
      env:
        APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}

  # Deploy web app
  deploy_web:
    name: Deploy Web App
    runs-on: ubuntu-latest
    needs: [prepare_release, create_github_release]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Download web build
      uses: actions/download-artifact@v4
      with:
        pattern: production-build-web-*
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: web-build/
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  # Post-release monitoring
  post_release_monitoring:
    name: Post-Release Monitoring
    runs-on: ubuntu-latest
    needs: [prepare_release, deploy_stores, deploy_web]
    if: always()
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Monitor app store deployments
      run: |
        echo "Monitoring app store deployments for version ${{ needs.prepare_release.outputs.version }}"
        
        # Check Google Play Console status
        echo "Checking Google Play Console..."
        
        # Check App Store Connect status
        echo "Checking App Store Connect..."
        
        # Set up monitoring alerts
        echo "Setting up monitoring alerts..."
    
    - name: Monitor web deployment
      run: |
        echo "Monitoring web deployment health..."
        
        # Health check
        curl -f https://${{ github.repository_owner }}.github.io/${{ github.repository_name }}/ || exit 1
        
        # Performance check
        echo "Running performance checks..."
    
    - name: Send release notifications
      uses: actions/github-script@v7
      with:
        script: |
          const version = '${{ needs.prepare_release.outputs.version }}';
          const isPrerelease = '${{ needs.prepare_release.outputs.is_prerelease }}' === 'true';
          const deployStores = '${{ needs.deploy_stores.result }}';
          const deployWeb = '${{ needs.deploy_web.result }}';
          
          const emoji = isPrerelease ? '🧪' : '🚀';
          const releaseType = isPrerelease ? 'Pre-release' : 'Release';
          
          let message = `${emoji} **${releaseType} ${version} Deployed Successfully!**\n\n`;
          message += `### Deployment Status\n`;
          message += `- Google Play Store: ${deployStores === 'success' ? '✅' : '❌'}\n`;
          message += `- App Store: ${deployStores === 'success' ? '✅' : '❌'}\n`;
          message += `- Web App: ${deployWeb === 'success' ? '✅' : '❌'}\n\n`;
          message += `### Links\n`;
          message += `- [GitHub Release](https://github.com/${{ github.repository }}/releases/tag/${version})\n`;
          message += `- [Web App](https://${{ github.repository_owner }}.github.io/${{ github.repository_name }}/)\n\n`;
          message += `Build #${{ github.run_number }} | Commit: ${{ github.sha }}\n`;
          
          console.log(message);
          
          // Here you could send to Slack, Discord, email, etc.
          // await sendSlackNotification(message);
          // await sendDiscordNotification(message);
    
    - name: Update monitoring dashboards
      run: |
        echo "Updating monitoring dashboards with new release info..."
        # Add integration with monitoring services (DataDog, New Relic, etc.)